title: Russian Department 2023-24 newsletter
description: Summer, Fall, and Spring activities and milestones as submitted by faculty and students

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
